#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 18 14:06:23 2020

@author: joe
"""
import numpy as np
import pandas as pd
import math


def fs(leng,column,pfn):
    global variable
    variable = []
    f = open (pfn, "r")

    for line in f:
        data = f.readlines()
 
    variable = []
    value = 0
    while value < leng:
        if value>0:
            dx = data[value].split()
            variable.append(dx[column])
            value+=1
        else:
         value+=1
    return(variable)


def split(leng, pfn):
    #pfn = "peptide.gro"
    peptide_gro = {}

    v = 0
    while v<6:
        peptide_gro["var"+str(v)] = fs(leng,v,pfn)
        v+=1

    global Pep_Name
    Pep_Name = (peptide_gro['var0'])
    global Atom_Name
    Atom_Name = (peptide_gro['var1'])
    global Atom_Number
    Atom_Number = (peptide_gro['var2'])
    global X_Coor
    X_Coor = (peptide_gro['var3'])
    global Y_Coor
    Y_Coor = (peptide_gro['var4'])
    global Z_Coor
    Z_Coor = (peptide_gro['var5'])



FNO = "TESTPEP.gro"
NUMPEPT = 400
SIZE = 14
FileName = "TEST \n"
FileLen = 6137

with open ("au-cubic.gro", "r") as f:
    with open (FNO, "w") as fo:
        fo.write(FileName)
        fo.write("%5s \n" %(FileLen))
        ln = 0
        b = 0
        for line in f:
            if ln < 2:
                ln+=1
            elif ln > 5627880:
                break
            else:
                col = line.split()                
                pp = col[0]
                atom = str(col[1]) 
                x = float(col[-6])
                y = float(col[-5])
                z = float(col[-4])
                r = math.sqrt((x**2)+(y**2)+(z**2))
                if ln % 2 == 0:
                    if x <= 2 and x >= 0 and y <=5 and y >= 0 and z <= 5 and z >=0 :
                        fo.write(line)
                        ln+=1
                        b+=1
                    else:
                        ln+=1
                else:
                    if b == 1:
                        fo.write(line)
                        ln+=1
                        b-=1
                    else:      
                        ln+=1

split(292, "peptide.gro")
c1 = 0
c2=0
for v in X_Coor:
        with open (FNO, "a") as f:
            x = float(X_Coor[c2])+2
            y = float(Y_Coor[c2])+2.5
            z = float(Z_Coor[c2])+2.5
            PN = (Pep_Name[c2])
            ANa = (Atom_Name[c2])
            ANu = (Atom_Number[c2])
            f.write("%8s%7s%5d%8.3f%8.3f%8.3f%8.3f%8.3f%8.3f \n" % (PN, ANa, c2,x,y,z,0,0,0))
            #print(XPOINTS[c1])
            c2+=1
c1+=1


with open (FNO, "a") as f:
    f.write("%10.5f%10.5f%10.5f \n" % (10,5,5))    
     
