#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 10 14:21:21 2019
@author: joe
"""
###############################################################################

#FUNCTIONS FROM PAPER
    
###############################################################################   
import math

#Creates the spherical lines
def spherical_coordinate(x,y):
    return [math.cos(x) * math.cos(y),
            math.sin(x) * math.cos(y), math.sin(y)]

#Creates the actual N points    
def NX(n, x):
    pts=[]
    start = (-1. + 1. / (n - 1.) )
    increment = (2. - 2. / (n -1.)) / (n -1.)
    for j in range(0, n):
        s = start + j * increment
        pts.append(
        spherical_coordinate(
        s * x, math.pi / 2. *
        math.copysign(1, s) *
        (1. - math.sqrt(1. -abs(s)))
        ))
       
    return pts

#Generates complete set of points in a list of lists
def generate_points(n):
    return NX(n, 0.1 + 1.2 * n)

###############################################################################

#MY FUNCTIONS
    
###############################################################################   
#Split the generated points into XYZ and multiply by radius.
def xyz(col):
    global points
    points = []
    c = 0
    for v in genplot:
        value = ((genplot[c][col])/2*SIZE)
        points.append(value)
        c+=1

#A function to open a file = pfn. Split each column into a list with length leng
# depending on value of column (0-6 in pfn), it is saved to "variable"
def fs(leng,column,pfn):
    global variable
    variable = []
    f = open (pfn, "r")

    for line in f:
        data = f.readlines()

    variable = []
    value = 0
    while value < leng:
        if value>0:
            dx = data[value].split()
            variable.append(dx[column])
            value+=1
        else:
         value+=1
    #print(variable)
    return(variable)


#Split uses the func fn, to open pfn and save each column to a list named Varx, 
# where x = column num. These are then replaced with actual names and added to
# a dictionary of lists with the name as the key.
def splitx(leng):
    pfn = "peptideX.gro"
    #pep_len(pfn)    
    
    peptide_gro = {}
    
    v = 0
    while v<6:
        peptide_gro["var"+str(v)] = fs(leng,v,pfn)
        v+=1
    
    
    global Pep_Name
    Pep_Name = (peptide_gro['var0'])
    global Atom_Name
    Atom_Name = (peptide_gro['var1'])
    global Atom_Number
    Atom_Number = (peptide_gro['var2'])
    global X_Coor
    X_Coor = (peptide_gro['var3'])
    global Y_Coor
    Y_Coor = (peptide_gro['var4'])
    global Z_Coor
    Z_Coor = (peptide_gro['var5'])
    
def splitz(leng):
    pfn = "peptideZ.gro"
    #pep_len(pfn)    
    
    peptide_gro = {}
    
    v = 0
    while v<6:
        peptide_gro["var"+str(v)] = fs(leng,v,pfn)
        v+=1
    
    
    global Pep_Name
    Pep_Name = (peptide_gro['var0'])
    global Atom_Name
    Atom_Name = (peptide_gro['var1'])
    global Atom_Number
    Atom_Number = (peptide_gro['var2'])
    global X_Coor
    X_Coor = (peptide_gro['var3'])
    global Y_Coor
    Y_Coor = (peptide_gro['var4'])
    global Z_Coor
    Z_Coor = (peptide_gro['var5'])

def spherical():
    c = 0
    global R
    R = math.sqrt((XPOINTS[0]**2)+(YPOINTS[0]**2)+(ZPOINTS[0]**2))
    global THETAS
    THETAS = []
    global RHOS
    RHOS = []
    for v in XPOINTS:
        RHO = math.acos(ZPOINTS[c]/R)
        RHOS.append(RHO)
        THETA =  math.atan2(YPOINTS[c], XPOINTS[c])
        THETAS.append(THETA)
        c+=1
    print("T,R",THETAS, RHOS)
    
    
def POINTS():
    global XNEWS
    XNEWS = []
    global YNEWS
    YNEWS = []
    global ZNEWS
    ZNEWS= []

    c = 0
    for x in XPOINTS:
        XNEW = R*math.sin(RHOS[c])*math.cos(THETAS[c])
        XNEWS.append(XNEW)
        YNEW = R*math.sin(RHOS[c])*math.sin(THETAS[c])
        YNEWS.append(YNEW)
        ZNEW = R*math.cos(RHOS[c])
        ZNEWS.append(ZNEW)
        c+=1

    return XNEWS, YNEWS, ZNEWS
###############################################################################

#Defining the system
    
###############################################################################    
FNO = "TESTPEP.gro"
NUMPEPT = 900
SIZE = 14


###############################################################################

#RUNNING
    
###############################################################################   
genplot = (generate_points(NUMPEPT))
xyz(0)
XPOINTS = points
xyz(1)
YPOINTS = points
xyz(2)
ZPOINTS = points


#testPOINTS
XPOINTS = [7,-7,0,0,0,0]
YPOINTS = [0,0,7,-7,0,0]
ZPOINTS = [0,0,0,0,7,-7]





FileName = "TEST \n"
FileLen = 1812
c=0
with open (FNO, "a") as f:
    f.write(FileName)
    f.write("%5s \n" %(FileLen))
    for v in XPOINTS: 
        xa = (XPOINTS[c])
        ya = (YPOINTS[c])
        za = (ZPOINTS[c])
        q = c+1
        p=(q)  
        f.write("%5d%-5s%5s%5d%8.3f%8.3f%8.3f \n" % (p, "AU2", "AUB", p, xa, ya, za))
        c+=1  

spherical()
        
c1 = 0
for v in XPOINTS: 
    if 3.5 > ZPOINTS[c1] > -3.5:

        splitx(302)
    
        theta = THETAS[c1]
        print(c1, "this thetaaa \n", theta)
        rho = RHOS[c1]
        print(c1, "RHOOOOOO \n", rho)
        c2=0
        for v in X_Coor:
            with open (FNO, "a") as f:
                xcoor = float(X_Coor[c2])+7
                #print(xcoor)
                ycoor = float(Y_Coor[c2])
                zcoor = float(Z_Coor[c2])
                RP = math.sqrt((xcoor**2)+(ycoor**2)+(zcoor**2))
                
                rhoINIT = math.acos(zcoor/ RP)
                #print(c1,"rhooinittt \n", rhoINIT)
                #rhoFINAL = rho  +(rhoINIT-(math.pi/2))
                rhoDELTA = rho - 1.571
                print(rhoDELTA)
                rhoFINAL = rhoDELTA + rhoINIT 
                print(c1, "rhoFINALLLLEEE", rhoFINAL)
    
               
                thetaINIT = math.atan2(ycoor,xcoor)
                #print(c1, "thetai", thetaINIT)
                thetaDELTA = theta 
                thetaFINAL =  theta + thetaINIT
                
                #print(c1, "thetaFINAL",thetaFINAL)
                
                XNEWCOOR = RP*(math.sin(rhoFINAL)*math.cos(thetaFINAL))
                #print(c1,"xxxxxx", XNEWCOOR)
                #XNEWCOOR = RP*math.cos(thetaFINAL)
                YNEWCOOR = RP*(math.sin(rhoFINAL)*math.sin(thetaFINAL))
                #print(c1,"yyyy",YNEWCOOR)
                #YNEWCOOR = RP*math.sin(thetaFINAL)
                ZNEWCOOR = RP*math.cos(rhoFINAL)            
                #print(c1, "zzzzz", ZNEWCOOR)
                PN = (Pep_Name[c2])
                
                ANa = (Atom_Name[c2])
                ANu = (Atom_Number[c2])
                x = float(XNEWCOOR)
                #print(x)
                y = float(YNEWCOOR)
                #print(y)            
                z = float(ZNEWCOOR)            
                #print(z)
                #print("\n")
                f.write("%8s%7s%5d%8.3f%8.3f%8.3f \n" % (PN, ANa, c2,x,y,z))
                #f.write ("%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%5i \n" %(xcoor, ycoor, zcoor, RP,theta,thetaINIT,thetaFINAL,rho,rhoINIT, rhoFINAL, x, y, z, c2))
                #f.write ("%10f%10f%10f%10f%5i \n" %(theta,thetaINIT,thetaDELTA,thetaFINAL,c2))
                #f.write ("%10f%10f%10f%10f%5i \n" %(rho,rhoINIT,rhoDELTA,rhoFINAL,c2))
                c2+=1 
    
    else:
        splitz(302)
    
        theta = THETAS[c1]
        print(c1, "this thetaaa \n", theta)
        rho = RHOS[c1]
        print(c1, "RHOOOOOO \n", rho)
        c2=0
        for v in X_Coor:
            with open (FNO, "a") as f:
                xcoor = float(X_Coor[c2])
                #print(xcoor)
                ycoor = float(Y_Coor[c2])
                zcoor = float(Z_Coor[c2])+7
                RP = math.sqrt((xcoor**2)+(ycoor**2)+(zcoor**2))
                
                rhoINIT = math.acos(zcoor/ RP)
                #print(c1,"rhooinittt \n", rhoINIT)
                #rhoFINAL = rho  +(rhoINIT-(math.pi/2))
                rhoDELTA = rho
                print(rhoDELTA)
                rhoFINAL = rhoDELTA + rhoINIT 
                print(c1, "rhoFINALLLLEEE", rhoFINAL)
    
               
                thetaINIT = math.atan2(ycoor,xcoor)
                #print(c1, "thetai", thetaINIT)
                thetaDELTA = theta 
                thetaFINAL =  theta + thetaINIT
                
                #print(c1, "thetaFINAL",thetaFINAL)
                
                XNEWCOOR = RP*(math.sin(rhoFINAL)*math.cos(thetaFINAL))
                #print(c1,"xxxxxx", XNEWCOOR)
                #XNEWCOOR = RP*math.cos(thetaFINAL)
                YNEWCOOR = RP*(math.sin(rhoFINAL)*math.sin(thetaFINAL))
                #print(c1,"yyyy",YNEWCOOR)
                #YNEWCOOR = RP*math.sin(thetaFINAL)
                ZNEWCOOR = RP*math.cos(rhoFINAL)            
                #print(c1, "zzzzz", ZNEWCOOR)
                PN = (Pep_Name[c2])
                
                ANa = (Atom_Name[c2])
                ANu = (Atom_Number[c2])
                x = float(XNEWCOOR)
                #print(x)
                y = float(YNEWCOOR)
                #print(y)            
                z = float(ZNEWCOOR)            
                #print(z)
                #print("\n")
                f.write("%8s%7s%5d%8.3f%8.3f%8.3f \n" % (PN, ANa, c2,x,y,z))
                #f.write ("%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%10f,%5i \n" %(xcoor, ycoor, zcoor, RP,theta,thetaINIT,thetaFINAL,rho,rhoINIT, rhoFINAL, x, y, z, c2))
                #f.write ("%10f%10f%10f%10f%5i \n" %(theta,thetaINIT,thetaDELTA,thetaFINAL,c2))
                #f.write ("%10f%10f%10f%10f%5i \n" %(rho,rhoINIT,rhoDELTA,rhoFINAL,c2))
                c2+=1 
    

    c1+=1





with open (FNO, "a") as f:
    f.write("%10.5f%10.5f%10.5f \n" % (2,2,2))     
    
