#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  4 10:29:50 2019

@author: josephwallace
"""
'''
###############################################################################
def func(m,i):
    l = []
    x = 0
    for p in linelist:
        if x>= m:
            if x%i == 0:
                l.append(linelist[x])
        #print(linelist[x])
                x+=1
            else:
                x+=1
        else:
            x+=1
    print(l)
###############################################################################
with open("rama_ic.xvg") as f:
    linelist = f.readlines()



func(1,16)


'''
##############################################################################


#l is number in the list, i is column, 
def fs(l,i):
    global h

    f = open ("rama_ic.xvg", "r")

    for line in f:
        data = f.readlines()
    
    h = []
    v = 0
    while v < l:
        if i<2:
            
            dx = data[v].split()
            h.append(float(dx[i]))
            #^for columns 0 and 1
            v+=1
        else:
            dx = data[v].split()
            h.append(dx[i])
            #^for columns 2
            #print(dx[0])
            v+=1
    #print(h)
    #print(h[0])
    
##############################################################################
def file_len(fname):
    with open(fname) as f:
        for i, l in enumerate(f):
            pass
    print(i + 1)
##############################################################################
file_len("rama_ic.xvg")


fs(40079,0)
f1 = h

fs(40079,1)
f2 = h

fs(40079,2)

f3 = h

print("h",h[0])
print("f1",f1[0])
print("f2",f2[0])
print("f3",f3[0])

##############################################################################
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.RandomState(0)
x = f1
y = f2

plt.xlim = (-180, 180)
plt.ylim = (-180, 180)
plt.scatter(x, y)











